[package]
build = "build.rs"
edition = "2024"
name = "launcher"
version = "2.0.0"

[dependencies]
configparser = "3.2.0"
windows-sys = { version = "0.61.2", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Environment",
  "Win32_System_Threading",
  "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
winresource = "0.1.31"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.dev.package."*"]
debug = false
